### ISSUE TITLE
can not make it working

### ISSUE THREAD

**Issue by majidshokrolahi** [MFaisalHyder/REST_API#1]
Hi, 
I have downloaded the project, and I have updated the file gradle.prefs in .setting. When I tried to build it, There was an error in Spring dependency, I have search and I have found this solution : 
Adding : `classpath("org.springframework.boot:spring-boot-gradle-plugin:1.3.5.RELEASE") `
into dependencies, in file the **build.gradle.**
I have also change the IP in your code and I have put "localhost"
Then I could bulid and run the app using: `gradle clean bootRun`
The server starts without any error, but when i navigate into "localhost:8080" or any other path defined in the project,i can not see any thing:
`This localhost page can’t be found
No webpage was found for the web address: http://localhost:8080/home
HTTP ERROR 404`

Can you please help me in this regard ?

**Comment by mfaisalhyder** [comment]
First page is not localhost:8080/home

It is on context path : /Api i.e. http://<localhost_Or_Ip>:<8080>/Api now you have home page.

**Comment by majidshokrolahi** [comment]
Thank you Faisal. Now I could run app in localhost. But I have problem when I deploy it in app engine. Spring Boot uses Servlet 3.0 APIs but GAE does support just Servlet 2.5 APIs. I have tried to change the configuration to not use Spring boot, but I have not succeeded. I am new with Spring boot and Gradle. Is it possible for you to explain for me how to make another version with Maven which works with Jetty or tomcat ?

**Comment by majidshokrolahi** [comment]
Can you kindly change this project to a maven project which I can deploy it in Tomcat ?

**Comment by mfaisalhyder** [comment]
I have emailed you the solution.

**Comment by mfaisalhyder** [comment]
Yes, Majid you can, kindly follow this article,
https://www.mkyong.com/spring-boot/spring-boot-jetty-as-embedded-server/
